name: KoroxoUtil1
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #---------------------------#
      - name: Cache
        uses: actions/cache@v3.0.11
        with:
          path: ./KoroxoOS_v1
          key: zx2he9
      - name: Set up NASM
        uses: ilammy/setup-nasm@v1.4.0
        with:
          version: 2.15.05
          platform: linux
      - name: Converter
        working-directory: ./KoroxoOS_v1
        run: compile.sh
      - name: Debug
        working-directory: ./KoroxoOS_v1
        run: |
          nano debug
          n boot.bin
          1 0
          w 0 0 0 1
      - name: Kernel
        working-directory: ./KoroxoOS_v1
        run: |
          kernel.bin copy
          a:\kernel.bin
