name: KoroxoUtil1
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #---------------------------#
      - name: Set up NASM
        uses: ilammy/setup-nasm@v1.4.0
        with:
          version: 2.15.05
          platform: linux
      - name: Converter
        run: |
          cd ../../KoroxoOS_v1
          compile.sh
      - name: Debug
        run: |
          nano debug
          n boot.bin
          1 0
          w 0 0 0 1
      - name: Kernel
        run: |
          kernel.bin copy
          a:\kernel.bin
