name: ISO Make
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #---------------------------#
      - name: qemu install
        run: echo closed
      - name: Set up NASM
        uses: ilammy/setup-nasm@v1.4.0
        with:
          version: 2.15.05
          platform: linux
          
